version: "3.9"

services: 
  redis:
    image: redis:alpine
    ports: 
      - 6379:6379
    restart: always
  webapi:
    build: .
    ports: 
      - 8080:8080
    links: 
      - redis
    restart: always
